return {
    "2 arm stroke",
    "360",
    "5x30 1",
    "5x30 down",
    "7 Rings Dance",
    "8-Bit Shuffle",
    "9mm Go Bang!",
    "A Bar Song",
    "A Loving Present",
    "A Tear In Space",
    "A Tear In Space",
    "A Vlog",
    "A Warrior Prepares",
    "A dice",
    "AFK",
    "APT Dance",
    "APT V2",
    "APT",
    "Abracadabra",
    "Accolades",
    "Act Like A Robot",
    "Active Step",
    "Addendum",
    "Advanced Math",
    "Aerostep",
    "Ain't It Fun",
    "Ain It Fun",
    "Air Guitar",
    "Air Punch",
    "Air Shredder",
    "Airbone",
    "Airdancer",
    "Alibi V2",
    "Alibi",
    "Alive",
    "All About That Bass",
    "All About The Bass two",
    "All About The Bass",
    "All For You",
    "All I Want For Christmas Is You",
    "All I Want For Christmas",
    "All Night",
    "AllowSleep's Vibe",
    "Altima Shuffle",
    "Amber Dance",
    "Ambitious",
    "Americano",
    "Anthony Shuffle",
    "Anxiety",
    "Apple Apple",
    "Apple Dance",
    "Apple Pen",
    "Apple V2",
    "Apple",
    "Arabadan Atladi",
    "Arachrobatics",
    "Arm Blocky",
    "Arm Wiggle",
    "Arm the Pumpkin!",
    "Around The Clock",
    "Ask Me",
    "Ass Eat",
    "Assumptions Redux",
    "Assumptions Whisk",
    "Assumptions",
    "Astro Slide",
    "At 3AM",
    "Attraction",
    "Automata",
    "Aw Snap!",
    "Awesome Strut",
    "BBoom 1",
    "BBoom 2",
    "Ba Ba Ba",
    "Back On 74",
    "Backflip",
    "Backshots",
    "Backstroke",
    "Bad Boy",
    "Bad Romance",
    "Baller",
    "Ballerina",
    "Ballet Montage",
    "Balletic",
    "Ballsy",
    "Banana Shake",
    "Banjo Step",
    "Bara Bere",
    "Baseball Bill",
    "Bass Down Low",
    "Bawk Bawk",
    "Be Gone",
    "Be Happy",
    "Be My Lover",
    "Bean Bag",
    "Bear Hug",
    "Beat It",
    "Beating Combo",
    "Beckon",
    "Bed Chem II",
    "Bed Chem",
    "Been Away",
    "Beep Boop",
    "Bell Ringer",
    "Belly Dance",
    "Belly Dancin",
    "Belly Spin",
    "Bet",
    "Better Than",
    "Bhangra Boogie",
    "Big Dawgs",
    "Big Swastika",
    "Bik Dance",
    "Bill",
    "Billy Bounce",
    "Bim Bam Boom",
    "Bim Bam Toi",
    "Bimdoll",
    "Bird Call",
    "Bird Surf",
    "Birds Of A Feather",
    "Bizcochito",
    "Blade",
    "Blah Blah Blah",
    "Blastin",
    "Blinding Lights",
    "Bling Bang Born",
    "Bling",
    "Blood Pop 2",
    "Blood Pop",
    "Bloomin Bouquet",
    "Blox Friends",
    "Bobbin'",
    "Bodybuilder",
    "Bold Stance",
    "Bombastic",
    "Boneless",
    "Boney Bounce",
    "Boo'd Up Groove",
    "Boogie Bomb",
    "Boogie Down",
    "Boogie Woogie",
    "Boom Twerk",
    "Boom!",
    "Boop!",
    "Boosting Ki",
    "Boots 'N' Cats",
    "Boppin",
    "Boston Breakdance",
    "Bounce Berry",
    "Bounce Wit It",
    "Bounce",
    "Bouncy Twirl",
    "Bouncy",
    "Boy's A Liar",
    "Bracelets Of Hephaestus",
    "Brain Eater",
    "Brass Strut",
    "Brass Wiggle",
    "Bratty",
    "Break Free",
    "Breakdance Routine",
    "Breakdown",
    "Breakin",
    "Breakneck",
    "Breezy",
    "Bright Moves",
    "Bring It Around",
    "Brite Moves",
    "Brodyquest",
    "Brokenhearted",
    "Brooklyn Pop",
    "Brooklyn Uprock",
    "Bubble Shuffle",
    "Bubblegum",
    "Bubbles!",
    "Buckets",
    "Buckle Up",
    "Buffalo Ranch",
    "Bugi-Vugi",
    "Build Up",
    "Bullet Ballet",
    "Bullet Dodge Ballet",
    "Bulletfetti",
    "Bumblebee",
    "Bunny Dance",
    "Bunny Hop (Roblox)",
    "Bunny Hop",
    "Bunny Party",
    "Burpee",
    "Business Up Front",
    "Bust a Move",
    "Bye Bye Bye FN",
    "Bye Bye Bye",
    "C R A B V I B E",
    "Caffeinated",
    "Cairo",
    "Calamity",
    "California Gurls",
    "California Love",
    "Camel by Camel!",
    "Cammy Flip",
    "Can't Take My Eyes Off You",
    "Can't Touch This",
    "Cancun Dance",
    "Cannon Spike",
    "Cap Kick",
    "Capoeira",
    "Car Shearer Dance",
    "Caramelldansen 2",
    "Caramelldansen",
    "Cardistry",
    "Carefree",
    "Carlton",
    "Carolina Step",
    "Cartwheelin'",
    "Caves In",
    "Celebrate Me",
    "Chacha",
    "Chainsaw Dance",
    "Challenge",
    "Champ's Clap",
    "Champion Struggle",
    "Champion Celebration",
    "Charging Blast",
    "Charging Up",
    "Charleston",
    "Chase Me Down",
    "Check",
    "Cheer It Mello",
    "Cheer On",
    "Cheer Up",
    "Cheerful Vibe",
    "Cheers",
    "Cheesecake",
    "Chef's Special",
    "Chicken Baby",
    "Chicken Dance",
    "Chicken Dinner Vibe",
    "Chicken Egg",
    "Chicken Mama",
    "Chicken Papa",
    "Chicken Shuffle",
    "Chicken Stride",
    "Chicken Wing It",
    "Chicken",
    "Chikiri Bai Bai",
    "Chimichanga!",
    "Chronoshift",
    "Clap It Mello",
    "Clap",
    "Classic Justice",
    "Classy Feeling",
    "Classy Strut",
    "Classy",
    "Clean Groove",
    "Clear Out!",
    "Click Click Flash",
    "Click",
    "Cluck Strut",
    "Cmere",
    "Collaborative Dance",
    "Committed",
    "Company Jig",
    "Confused",
    "Conga",
    "Controller Crew",
    "Copines",
    "Cotton Candy",
    "Crabby",
    "Crackdown",
    "Cradle",
    "Crank That",
    "Crazy Crazy",
    "Crazy Feet",
    "Crazyboy",
    "Creative",
    "Criminals",
    "Criss Cross",
    "Crossbounce",
    "Crossbow Dance",
    "Crossed Out",
    "Crown",
    "Crowning Achievement",
    "Cruisin'",
    "Crushing It",
    "Cult Classic",
    "Culture Festival Dance",
    "Cupid's Arrow",
    "Cupid",
    "Cure For Me",
    "Cut It",
    "Cutely Dancing",
    "Cyberdyne Salute",
    "DAME UN GRR",
    "DANCE A",
    "DANCE B",
    "DDU-DU DDU-DU",
    "DIVA",
    "DJ Caliber",
    "DON'T HURT EM'!",
    "Da Whip",
    "Dame Tu Cosita",
    "Dance Monkey",
    "Dance Moves",
    "Dance Off",
    "Dance Potion",
    "Dance Therapy",
    "Dance2013",
    "Dancery",
    "Dancin' Domino",
    "Dancin' Shuffle 2",
    "Dancin' Shuffle 3",
    "Dancin' Shuffle 4",
    "Dancin' Shuffle",
    "Dancing Cat",
    "Dancing Dead",
    "Dante Dance",
    "Dark Side",
    "Dawn",
    "Daydream",
    "Daywalker's Kata",
    "Deep Cuts",
    "Deep Dab",
    "Deep End",
    "Deep Explorer",
    "Denial",
    "Denied",
    "Deposits",
    "Desirable",
    "Desperado Jam",
    "Devotion",
    "Dexter Rampage!",
    "Dia Delicia",
    "Dick Jerk",
    "Dick Slap",
    "Dificil Contrar",
    "Dill With It",
    "Dimensional",
    "Dinero",
    "Dip",
    "Dirtbike Challenge",
    "Disco (Surf Curse)",
    "Disco Dance",
    "Disco Fever",
    "Disco Fievre",
    "Disco Night",
    "Disco Pointer",
    "Disco",
    "Disrespectful Dance",
    "Distraction Dance",
    "Diva Fever",
    "Do That Thang",
    "Do The 'Split",
    "Do The Flop!",
    "Do The Move",
    "Dog Leg",
    "Doktorspiele",
    "Domino",
    "Don't Mine At Night",
    "Don't Start Now",
    "Doodle",
    "Dosido",
    "Double Blaster",
    "Double Hops",
    "Double Step",
    "Double Tap",
    "Double Up",
    "Dougie Fresh",
    "Down The Drain",
    "Downtown Funk",
    "Downtown",
    "Dragon Stance",
    "Dragon's Rise",
    "Dream Feet",
    "Dream Stance",
    "Dreamer",
    "Dreamy Keys",
    "Drip",
    "Drippin' Flavour",
    "Dualies T",
    "Dubstep Jumps",
    "Dubstep Wave",
    "Dust Your Boots Off",
    "Dxrk Walk",
    "Dynamic Shuffle",
    "Dynamite",
    "Electro Shuffle",
    "Electro Swing",
    "Elegant Bow",
    "Elegant",
    "Elite Agent",
    "Empress Fan Dance",
    "Empty Out Your Pockets",
    "Empty Pockets",
    "Energetic Vibe",
    "Enigmatic Killer",
    "Enlightened",
    "Entertainer",
    "Entranced",
    "Espresso V2",
    "Espresso",
    "Eu Queria Mudar",
    "Europapa",
    "Evan's Vibe",
    "Evasive Maneuvers",
    "Everybody Dance Now",
    "Everybody Loves Me",
    "Evil Plan (Just Go!)",
    "Evil Plan",
    "Expressionism",
    "Extraterrestrial",
    "Exum Shuffle",
    "Fabulous",
    "Facebang",
    "Facefuck",
    "Falling Deep",
    "Fanciful",
    "Fancy Feet",
    "Fancy Flapping",
    "Fancy Flourishes",
    "Fancy Footwork FN",
    "Fancy Footwork",
    "Fandangle",
    "Fantasy Showoff",
    "Fast Feet",
    "Fast Slow Disco",
    "Feel Good",
    "Feel It",
    "Feel The Flow",
    "Feelin Jaunty",
    "Feelin' Hype",
    "Feelin' Right",
    "Feelin' Royal",
    "Feeling",
    "Fight",
    "Fighter's Moves",
    "Figure Skating Freestyle",
    "Finally 18",
    "Finesse",
    "Finger Shot",
    "Finger Wag",
    "Firework",
    "First Month",
    "Fishin",
    "Fishy Flourish",
    "Fist Bump",
    "Fist Pump",
    "Fitness Stomp",
    "Flamenco",
    "Flapper",
    "Flashback Breakdown",
    "Flashbang Dance",
    "Flexible Moves",
    "Flippin' Amazing",
    "Flippin' Awesome",
    "Flippin' Incredible",
    "Floss",
    "Flourish",
    "Flux",
    "Fly Dance",
    "Fly High",
    "Fly To Tokyo",
    "Folk Dance",
    "Follow the Piper",
    "Forget Me Not",
    "Freaky Deaky",
    "Free Cuts",
    "Free Flow",
    "Freed",
    "Freedom Wheels",
    "Freemix",
    "Freestylin'",
    "Freewheelin'",
    "Fresh",
    "Friday Idle",
    "Friendly",
    "Fright Funk",
    "Frisbee Show",
    "Frog Dance",
    "Frolic",
    "From The Hip",
    "Full Tilt",
    "Funk Do Bounce",
    "Funky Jig",
    "Funky",
    "GEEK TIME",
    "GET JIGGY",
    "GGUM",
    "Gamma Overload",
    "Gangnam Style",
    "Garry's Dance",
    "Gentleman's Dab",
    "Get Funky",
    "Get Gone",
    "Get Griddy",
    "Get Loose",
    "Get Out of Your Mind",
    "Get Schwifty",
    "Get Started",
    "Get Sturdier",
    "Get Sturdy 2",
    "Get Sturdy",
    "Get butt f",
    "Ghost Samurai",
    "Giddy Up",
    "Give head",
    "Glitter",
    "Glorified Fresh",
    "Gloss",
    "Glow Out",
    "Glowsticks",
    "Glyphic",
    "Gnarly",
    "Go Ape",
    "Go Away",
    "Go Do It",
    "Go Mufasa",
    "Go With The Flow",
    "Go! Go! Go!",
    "Goated",
    "Golden",
    "Good Game, Well Played",
    "Good Guy",
    "Good Luck Babe",
    "Good Luck, Girl!",
    "Goofy Hump",
    "Goofy twerk",
    "Gravy Dance",
    "Gritty Grinder",
    "Groove Destroyer",
    "Groove Jam",
    "Groove Snaps",
    "Groovy Acrobatic",
    "Groovy Point",
    "Ground Pound",
    "Guitar Walk",
    "Gun Maracas",
    "Gunslinger Smokeshow",
    "Gwen-Step",
    "Gymnastics",
    "HANA",
    "HOTTOGO!",
    "HUMBLE.",
    "Hack n' Slash",
    "Halloween Tricks",
    "Hamood Habibi",
    "Han Solo",
    "Hand Signals",
    "Hand-Forged",
    "Hands Off!",
    "Hang Loose Celebration",
    "Hang Loose",
    "Hang On",
    "Happy Days",
    "Hard Whip",
    "Harmony",
    "Hatchback",
    "Havana",
    "Head Banger",
    "Head Tricks",
    "Headbanger",
    "Headlock",
    "Headstock Spin",
    "Heart Attack",
    "Heart Ceremony",
    "Heart of a King",
    "Heart-rizon",
    "Heart",
    "Heartbreak Shuffle",
    "Hearts For You V2",
    "Hearts For You",
    "Heavy Love",
    "Heel Click Breakdown",
    "Heel Toe Hop",
    "Heeseung Walk",
    "Hellfire Dance",
    "Hello Friend",
    "Here Here",
    "Here We Go",
    "Hero's Beacon",
    "Hey Mama",
    "Hey Now! Solo",
    "Hey Pookie",
    "Hi There",
    "High Five",
    "High Kicks",
    "High Noon",
    "High Steps",
    "Hip Hop Hero",
    "Hip Shop",
    "Hit Harder",
    "Hit It",
    "Hitchhiker",
    "Holiday",
    "Honorable Warrior",
    "Hood Vibin'",
    "Hooray",
    "Hootenanny",
    "Hoppity",
    "Hopscotch",
    "Hot Marat",
    "Hot Sauce",
    "Hot To Go!",
    "Hotline Bling",
    "Houdini",
    "House Party",
    "Hoverin",
    "How Sweet",
    "How You Like That",
    "Howl",
    "Hug Me More",
    "Hugo Hilaire 1",
    "Hugo Hilaire 2",
    "Hugo Hilaire 3",
    "Hugo Hilaire",
    "Hula Hoopin' Fail 2",
    "Hula Hoopin' Fail",
    "Hula Hoopin'",
    "Hula",
    "Humble",
    "Hunter Protocol",
    "Hurricane Hustle",
    "Hustla",
    "Hustle and Bop",
    "Hydout's Vibe",
    "Hype Hop",
    "Hype Medley",
    "Hype",
    "Hyped to Death",
    "Hypnot-Eyes",
    "I Aint Afraid",
    "I Declare!",
    "I Got Dominos",
    "I Like To Move It",
    "I Love It",
    "I Love You So",
    "I Wanna Run Away",
    "I am cofi",
    "I'll Miss You",
    "I'm A Mystery",
    "I'm Diamond",
    "I'm Out",
    "IDK",
    "IDOL",
    "Ice Ice Baby",
    "Illusive",
    "Im Only Human",
    "Image",
    "In Da Party",
    "In Ha Mood",
    "Independence",
    "Industry Baby",
    "Infectious",
    "Inferno",
    "Infinite Dab",
    "Infinite Shuffle",
    "Insert Laughter Here",
    "Intensity",
    "Intergalactic",
    "Internet Angel",
    "Interstellar Bass",
    "Interworld",
    "Introducing..",
    "Invader",
    "Invisible Stairs",
    "Island Vibes",
    "It's A Go!",
    "It's A Vibe",
    "It's Complicated",
    "It's Dynamite!",
    "It's Go Time!",
    "It's Good",
    "It's Ok I'm Ok",
    "It's True",
    "Its True",
    "Its ok I'm ok",
    "JT Coming",
    "Jabba Switchway",
    "Jake Dance",
    "Jamboree",
    "Jasmin",
    "Jaywalk",
    "Jazz Hands",
    "Jazz Skip",
    "Jazzy Dance",
    "Jerking Off",
    "Jet Signals",
    "Jiggle Jiggle",
    "Jitterbug",
    "Joker Stairs Dance",
    "Jon",
    "Joshiraku Dance",
    "Jubi Slide",
    "Jugglin'",
    "Jump Around",
    "Jump In The Cadillac",
    "Jump Jets",
    "Jump Jump",
    "Jumping Jacks",
    "Jumpstyle",
    "Jung Justice",
    "Junkrat Dance",
    "Just Because",
    "Just Do It",
    "Just Know",
    "Just Shuffle",
    "Just Wanna Dance",
    "KEEP UP!",
    "KEHLANI",
    "Katana",
    "Kawaii Desu Ne",
    "Kawaii Sturdy",
    "Kawaii!",
    "Kazotsky Kicking",
    "Keep Calm",
    "Keep It Mello",
    "Keep Me Satisfied",
    "Keyed Up",
    "Kick Ups",
    "Kickback",
    "Kindness Funk",
    "Kindness Punk",
    "Kiss It",
    "Kiss Kiss",
    "Knee Slapper",
    "Knife CT",
    "Knife T",
    "Knife Tricks",
    "Koi Dance",
    "Kotonai",
    "Lack Of Common Sense",
    "Lag-Train",
    "Laid Back Shuffle",
    "Lalka Shuffle",
    "Lambal",
    "Lanewyre",
    "Larger Than Life",
    "Laser Focused",
    "Laser Pointer",
    "Last Forever",
    "Laugh it Up",
    "Lavish",
    "Lazer Blast",
    "Lazy Shuffle",
    "Lean On",
    "Leapin",
    "Leave The Door Open",
    "Leg Dick",
    "Leg Swings",
    "Legal Reasons",
    "Leilt Elomr",
    "Leprechaun Hunt",
    "Let's Get It Started",
    "Let's Groove",
    "Let's Swing",
    "Lethal Amounts",
    "Lethal Dance",
    "Get It Started",
    "Go Back",
    "Levitate",
    "Lezginka Spectator",
    "Lezginka",
    "Lia Kim",
    "Liar",
    "Life Of A Noob",
    "Lights Up",
    "Like You",
    "Lil Bounce",
    "Lil Monster",
    "Lil Mower",
    "Lil Octane",
    "Lil Rover",
    "Lil Saucer",
    "Lil Warthog",
    "Lil' Carpet Ride",
    "Line Dance V2",
    "Line Dance",
    "Line Dancin'",
    "Linear Sides",
    "Little Buddy Was Sick",
    "Lively Walkin",
    "Living Large",
    "Llama Bell",
    "Llama Conga",
    "Lo-fi Headbang",
    "Lock It Up",
    "Loco Shake",
    "Lofi Headbang",
    "Look At Me",
    "Lookin' Good",
    "Looking Good",
    "Lorax Kid",
    "Lose Control",
    "Love It",
    "Love Letter",
    "Love Me Like I Love You",
    "Love Potions",
    "Lovesick Girls",
    "Low Opacity",
    "Low",
    "Lucid Dreams",
    "Luke",
    "Lunar Party",
    "Lyrics",
    "MONTAGEM LADRAO",
    "Ma Ma Ma",
    "Ma-Ya-Hi",
    "Macarena",
    "Made You Look",
    "Magnetic FN",
    "Make Some Waves",
    "Malevolent Mime",
    "Mamushi",
    "Mannrobics!",
    "Mansion Party",
    "Mansion Shuffle",
    "Mantra",
    "Marsh Walk",
    "Martial Arts Master",
    "Mashed Potato",
    "Mask Off",
    "Masked Psychic",
    "Master Of Seas",
    "Match My Freak",
    "Matrix Dodging",
    "Mawashi Geri",
    "Maximum Bounce",
    "Maya",
    "Mayahi",
    "Melodramatic",
    "Members Only",
    "Memories",
    "Meow Dance",
    "Metamorphosis Shuffle",
    "Mi Gente",
    "MiB Dance",
    "Midnight Moves",
    "Miku Live",
    "Miku Miku Beam",
    "Million Dollar Baby",
    "Millionaire",
    "Mime Time",
    "Mina Mintip",
    "Mind Blown",
    "Mine",
    "Minny Park",
    "Mio Honda Step",
    "Misery",
    "Moe's Assumptions",
    "Momoland",
    "Monkey Mosh",
    "Monster Mash!",
    "Monster Mash",
    "Moonbounce",
    "Moongazer",
    "Moonlit Mystery",
    "Motion Shuffle",
    "Motive",
    "Moulaga",
    "Move It",
    "Moze Shuffle",
    "Mr. Blue Sky",
    "Mr. Brightside",
    "Muffin Dance",
    "Murderous Chase",
    "Mwahaha",
    "My Honest Reaction",
    "My Idol",
    "My Main",
    "My Spark",
    "My World",
    "NYA Dance",
    "Nana Nana",
    "Napal Baji",
    "Nasty Girl",
    "Neighborly Hang",
    "Neo's Bullet Time",
    "Neo's Crazy Night",
    "Neo",
    "Neva Play",
    "Never Gonna",
    "New Jack Swingin'",
    "New Woman",
    "Newark Dance",
    "Nic Shuffle",
    "Night Out",
    "Night Time Shuffle",
    "Ninja Style",
    "Nishiyama",
    "Nitro Fueled",
    "No Cure",
    "No Limit",
    "No Sweat",
    "No Tears",
    "No Turn To Lose BG",
    "No Turn To Lose",
    "Northumbria Shuffle",
    "Not My Problem",
    "Now Without You",
    "Nuthin But A G Thang",
    "OG sex sleep",
    "OH NOES",
    "OMG I LOVE IT",
    "OMG",
    "Odd Shuffle",
    "Oh My Oh My",
    "Oh Shhh",
    "Oh Who Is You",
    "Oh shoot, a rat!",
    "Oki Doki",
    "Old School",
    "Old Town",
    "On The Floor",
    "On The Hook",
    "On Your Marks...",
    "Onda Onda",
    "One Dance",
    "One Time Victory",
    "Only One",
    "Oops I Did It Again",
    "Orange Justice",
    "Out Tha' Box",
    "Out West",
    "Outlaw",
    "Overdrive",
    "Overload",
    "POKA DANCE",
    "PWR Punch",
    "Pain",
    "Paint The Town Red",
    "Panuma",
    "Party Hips",
    "Party Rock",
    "Partyboy",
    "Passo Bem Solto",
    "Paws & Claws",
    "Pay Attention!",
    "Pay It Off",
    "Peace Out",
    "Peanut",
    "Air Punch",
    "Penguins",
    "Perfect Score",
    "Peter Parker",
    "Peter's Fall",
    "Phew!",
    "Phoenix",
    "Phone It In",
    "Phonky Town",
    "Phonky Turn",
    "Photograph",
    "Phut Hon",
    "Pick It Up",
    "Pico Celebration",
    "Picture Perfect",
    "Pina Colada",
    "Pirouette",
    "Planetary Vibe",
    "Play No Games",
    "Playing With Fire",
    "Please Please Please",
    "Plug Walk",
    "Point And Strut",
    "Poker Face",
    "Poki",
    "Poof!",
    "Pop Lock",
    "Pop Muzik",
    "Pop Star Step",
    "Poppy Love",
    "Popular Vibe",
    "Potted Groot Dance",
    "Pour It Up",
    "Power Step",
    "Powered Up",
    "Praise The Tomato",
    "Prayer in C",
    "Present Delivery",
    "Pretty Girl Mantra",
    "Pretty Scene Girl!",
    "Pride Wave",
    "Primo Moves",
    "Prince of Egypt",
    "Professional",
    "Pull Up!",
    "Pull Up",
    "Pump It Up",
    "Pump Me Up",
    "Pump Up The Jam",
    "Pumpernickel",
    "Punched Up",
    "Punching Practice",
    "Puppet Dance",
    "Pure Salt",
    "Quagmire Dance",
    "Questions",
    "Quick Bite",
    "Quick Step",
    "Quirk",
    "R U Mine",
    "ROCKWAVE",
    "RPG!",
    "Rabbit Dance",
    "Radical",
    "Rage Quit",
    "Rage",
    "Rain Check",
    "Rakuten Point",
    "Ralsei Duo",
    "Ralsei",
    "Rambunctious",
    "Rap Monster",
    "Rat Dance",
    "Ratatata",
    "Rawr",
    "Ready For Love",
    "Real High",
    "Real Slim Shady",
    "Real Slim",
    "Reality's Master",
    "Reanimated",
    "Reaper's Showtime",
    "Rebellious",
    "Reboot Shuffle",
    "Reciprocate",
    "Reckless",
    "Red Hot Shooter",
    "Red Light",
    "Reggae",
    "Remember The Time",
    "Renegade",
    "Resonance Shuffle",
    "Respect",
    "Restored",
    "Revel",
    "Revolving Geometry",
    "Rhythm Dancing",
    "Rhythm Of Chaos",
    "Rhythm Rider",
    "Rhythmical",
    "Ric Flair Shuffle",
    "Ric Flair",
    "Ricardo",
    "Riches",
    "Ride It",
    "Ride The Pony",
    "Ride The Vibe",
    "Right Round",
    "Rim Shot",
    "Rising Phoenix",
    "Road Shuffle",
    "Roar",
    "Robotic Moves",
    "Robotic Style",
    "Robotic Wobble",
    "Rock Out!",
    "Rock That Body",
    "Rock, Paper, Scissors!",
    "Rock",
    "Rocket Rodeo",
    "Rocket Spinner",
    "Rocky Road",
    "Rodeo",
    "Rogue-quette",
    "Roki",
    "Roll 'N Rock",
    "Roll Call",
    "Roll It Up",
    "Roll N' Rock",
    "Roller Vibes",
    "Rollie",
    "Rolly Rider",
    "Rootin' Tootin'",
    "Rough Dancer",
    "Roundabout",
    "Rowdy Rudolph",
    "Roy Purdy",
    "Royals",
    "Rude Shuffle",
    "Rumba",
    "Run Away",
    "Run It Down",
    "Run It",
    "Runaway Twerk",
    "Running Deadman",
    "Running Man",
    "Rushin' Around",
    "Russian Dance",
    "Russian Kick",
    "SMASH!",
    "SOU",
    "STUCK IN MY HEAD",
    "Sackin'",
    "Sad Claps",
    "Sahara",
    "Sail With Me",
    "Salsa Groove",
    "Salute",
    "Samba Shuffle",
    "Samba",
    "Samsara",
    "San Tan",
    "Sand Walk",
    "Sandstorm",
    "Sasquatchin",
    "Sassy Dancin'",
    "Sassy Showoff",
    "Sassy Walk",
    "Saturday Night Fever",
    "Saul",
    "Savage",
    "Saxophoned",
    "Say Cheese!",
    "Say So",
    "Scenario",
    "Schadenfreude",
    "Scissoring",
    "Scootin",
    "Scout Regiment Salute",
    "Screw Loose",
    "Secret Identity",
    "See It",
    "Segway Tour",
    "Self Head",
    "Servomechanical",
    "Settings Shuffle",
    "Shadow Dance",
    "Shadow Spar",
    "Shadowbox",
    "Shake  Slash",
    "Shake  Split",
    "Shake It To The Max",
    "Shake It Up",
    "Shamone",
    "Shaolin Sit-Up",
    "Shape Of You",
    "Shape Up",
    "Shaq Shimmy",
    "Sharp Circle twerk",
    "Sharp Shooter",
    "Shell",
    "Shhh.",
    "Shiba",
    "Shift",
    "Shimmer",
    "Shimmy Wiggle",
    "Shoryuken",
    "Shout!",
    "Show 'Em Off",
    "Show Ya",
    "Show You Off",
    "Showstopper",
    "Showtime",
    "Shuba Duck",
    "Shuffle Combo",
    "Shuffle",
    "Shum Shuffle",
    "Side Hustle",
    "Side Shuffle",
    "Side Step",
    "Side Stride",
    "Sideways Shift",
    "Sigma Boy",
    "Sign Spinner",
    "Signature Shuffle",
    "Sit 1",
    "Sit 2",
    "Sit 3",
    "Ska-Stra-Terrestrial",
    "Skele Dance",
    "Skibidi Dop Dop",
    "Skip",
    "Skull Breakdance",
    "Skull Cracker",
    "Slalom Style",
    "Slap Happy",
    "Slap It",
    "Slick",
    "Slickback V2",
    "Slickback",
    "Slide Stride",
    "Small Swastika",
    "Smeeze",
    "Smile (2)",
    "Smile",
    "Smitten",
    "Smooth Criminal",
    "Smooth Moves",
    "Smooth Operator",
    "Smooth Slide",
    "Smooth Winner",
    "Smooth",
    "Smug Victory",
    "Smuwug Dance",
    "Snapshot Swagger",
    "Snare Solo",
    "Snoop's Walk",
    "Snoops Walk",
    "Snoozefest",
    "So Am I",
    "So Fly",
    "So Low",
    "So Much More",
    "Soaked",
    "Soar Above",
    "Social Climber",
    "Socks",
    "Soda Pop",
    "Solo Tu",
    "Sonic Surfer",
    "Soul",
    "Sparkler",
    "Sparrow Run",
    "Specialist Seto",
    "Speedy Macarena",
    "Spicy Start",
    "Spider Dance",
    "Spidey Landing",
    "Spike It",
    "Spin Out 2",
    "Spin Out",
    "Spin Records",
    "Splash Damage",
    "Spongebob Shuffle",
    "Spongebob",
    "Spread Your Wings",
    "Spring-Loaded",
    "Springy",
    "Sprinkler",
    "Spy Shuffle",
    "Square Up",
    "Squash & Stretch",
    "Squat Kick",
    "Standing Bow",
    "Star Power",
    "Stare Don't Touch",
    "Stargazing",
    "Starlit",
    "Start It Up",
    "Starting Prance",
    "Statuesque",
    "Stay Afloat",
    "Stay Dance",
    "Stay",
    "Steady",
    "Steamed",
    "Step It Up",
    "Sticky",
    "Still Into You",
    "Stock Shuffle 2",
    "Stock Shuffle 3",
    "Stock Shuffle",
    "Stop!",
    "Stormy",
    "Strategy",
    "Streets",
    "Stride",
    "Stronger",
    "Strut",
    "Stuck",
    "Stutter Step",
    "Stylish Moonwalk",
    "Sucker",
    "Sugar Rush",
    "Suiii",
    "Summoning Jitsu",
    "Sumo Salt Throw",
    "Sundrop Dance",
    "Sunny Stroll",
    "Surfin' Bird",
    "Surfs Up",
    "Surround",
    "Survivorsault",
    "Susie",
    "Swag Shuffle",
    "Swag Surfin'",
    "Swag Up",
    "Swagger Strut",
    "Swaggin'",
    "Sway Around",
    "Sway Stomp",
    "Sway Sway",
    "Sway",
    "Sweaty",
    "Sweet Dreams",
    "Sweet Like Bubblegum BG",
    "Sweet Like Bubblegum",
    "Sweet Shot",
    "Sweet Victory",
    "Sweethearts",
    "Swing My Way",
    "Swing Rik",
    "Swing Victory",
    "Swing",
    "Swipe It",
    "Swish Swish",
    "Switchstep",
    "Swole Cat",
    "Symbol Of Peace",
    "Synth Step",
    "T-Pose",
    "TF Demoman",
    "TF Engineer",
    "TF Kazotsky Kick",
    "TF Scout",
    "TF Sniper",
    "Taca Taca",
    "Taco Time",
    "Tactical Moves",
    "Tagger's Groove",
    "TaiChi",
    "Tails Dance",
    "Take A Seat",
    "Take It Slow",
    "Take On Me",
    "Take The L",
    "Take a 'Bow",
    "Taste",
    "Taxi",
    "Team Ghost",
    "Technique",
    "Technoz",
    "Telekinetic Power Breakfast",
    "Tell Your Friend",
    "Tem",
    "Tempest Flight",
    "Testimony",
    "Thank You!",
    "That's So True",
    "The Airplane",
    "The Crane Kicker",
    "The Dip",
    "The Dogg",
    "The Falcon",
    "The Fire",
    "The Flow",
    "The Funny",
    "The Gangnam Style",
    "The Jig",
    "The King",
    "The Look",
    "The M.D.",
    "The Macarena",
    "The Magic Bomb",
    "The Masta",
    "The Middle",
    "The Nizmo",
    "The Pollo Dance",
    "The Poser",
    "The Pressure",
    "The Quick Style",
    "The Renegade",
    "The Rick Dance",
    "The Right Choice",
    "The Seven Seas",
    "The Shuffle",
    "The Silencer",
    "The Spark",
    "The Squabble",
    "The Worm",
    "They See Me",
    "Thick Of It",
    "Things She Said",
    "Think Mark Think",
    "This Is How We Do It",
    "Thread It",
    "Three Wise Monkeys",
    "Thriller Dance",
    "Thriller",
    "Tidy",
    "Tii",
    "Timeless",
    "Tina Boo",
    "Tiniest Violin",
    "Tippy Tap",
    "Tiramisu",
    "To The Beat",
    "To The Moon",
    "Toca Toca 2",
    "Toca Toca",
    "Tocked Off",
    "Tonight",
    "Too Fast",
    "Took The L",
    "Toosie Slide",
    "Tootsee",
    "Top Rock",
    "Tornado Spin",
    "Torture Dance",
    "Tossing Racks",
    "Total Control",
    "Touch",
    "Touching The Sky",
    "Tow Truck Surfer",
    "Towny",
    "Tra La La",
    "Tracer Dance",
    "Track Star",
    "Tragedy",
    "Training Moves",
    "Transylvania Groove",
    "Traveling In Time",
    "Travis Stargrab",
    "Treat Yourself",
    "Trinity's Kick",
    "Trippy Feet",
    "Triumph Step",
    "Triumphant",
    "True Contender",
    "True Heart",
    "Tuff Vibe",
    "Tunak Tunak Tun",
    "Turn Me Up",
    "Twerk On The Floor",
    "Twerk",
    "Twist and Lock",
    "Twist",
    "Twisty",
    "Tyler Shuffle",
    "U Can't C Me",
    "Unification",
    "United Chill Dance",
    "United Sponge",
    "Unlock It",
    "Uproar",
    "Uprock",
    "Upside Down & Inside Out",
    "Valentina Verve",
    "Valentines Surprise",
    "Valentino",
    "Vampire Bow",
    "Vamps",
    "Vegetable Juice",
    "Verve",
    "Very Good (222)",
    "Very Sneaky",
    "Vibe Only",
    "Vibe Shuffle",
    "Vibe",
    "Vibin'",
    "Victorian",
    "Victorious Breakdance",
    "Victorious Cluck",
    "Victorious Hype",
    "Victorious Shuffle",
    "Victorious Split",
    "Victorious Swimmer",
    "Victorious",
    "Victory Break",
    "Victory Display",
    "Victory Feelin'",
    "Victory Flip",
    "Victory Lap",
    "Victory Masked",
    "Victory Swag",
    "Victory Sway",
    "Victory Turn",
    "Vintage Moves",
    "Violent",
    "Violet Lover",
    "Virtual Insanity",
    "Vivacious",
    "Vogue Drop",
    "Volnova",
    "Volnovify",
    "Wacky Armed",
    "Waddle Away",
    "Wait No Come Back",
    "Waitin'",
    "Wake Up",
    "Walk The",
    "Walkin Pretty",
    "Walkin' Pretty",
    "Wanna Believe It",
    "Wanna See Me",
    "Warm-Up",
    "Waterworks",
    "Wavey Motion",
    "Waving Flow",
    "Wavy T",
    "We Like To Move It",
    "We Nailed It",
    "Wedding Party",
    "Wednesday",
    "Well Rounded",
    "Were Flying",
    "Western Boogie",
    "Western Rodeo",
    "What It Is",
    "What a Real",
    "What's Up Sketch (Flap)",
    "What's Up Sketch (Point)",
    "What Real",
    "When She Walk",
    "Where Are You",
    "Where Is Matt",
    "Where Ya Going",
    "Whip It",
    "Whiplash",
    "Whirlwind",
    "Whistle Dance",
    "White & Nerdy",
    "White Tiger",
    "Wicked",
    "Pirouette",
    "Wiggle",
    "Wigglin' Around",
    "Wiggly",
    "Wilbur Dance",
    "Wind Up",
    "Windmill Floss",
    "Windmill Shake",
    "Windmill Stomp",
    "Winner's Breakdance",
    "Winner's Dance",
    "Winner's Shuffle",
    "Wipe Me Down",
    "Witch Way",
    "With The Rhythm",
    "Without You",
    "Woke Up",
    "Woof Woof",
    "Work It",
    "Worker",
    "Wrap Me In Plastic",
    "Wrestler Shuffle",
    "Wrld Revolve",
    "Wu-Tang Is Forever",
    "XO (Only If You Say Yes)",
    "XO",
    "XOXO",
    "Y.M.C.A.",
    "YMCA",
    "YRN",
    "Yarn Ball",
    "Yay!",
    "Yee Haw",
    "Yo Bunny",
    "You Are Out!",
    "You Fool",
    "You Want Me",
    "You're A Winner",
    "You're Awesome",
    "Youjin Kim",
    "Your Favorite Martian",
    "Your Idol",
    "Zany",
    "Zaya Shuffle",
    "ZeroTwo",
    "Zom-Beam",
    "Zombie Shambles",
    "Zombified",
    "Zrde",
    "a thrust 2",
    "a thrust",
    "acro twerk 2",
    "afk animating",
    "aggressive slap",
    "aggressive twerk",
    "air hump",
    "all red",
    "ankle break death",
    "anthony thrust",
    "ass slap",
    "ass slapped",
    "aware of it thrust 2",
    "aware of it thrust",
    "back slide",
    "backflip fail",
    "bad guy",
    "bb belt",
    "bend twerk V2",
    "Big swastika (S15)",
    "blue shirt guy dance",
    "bounce twerk loop",
    "bounce twerk",
    "broken lay twerk",
    "chapa",
    "circle twerk",
    "close to you",
    "cofi",
    "come on dont hide",
    "corkscrew 2",
    "corkscrew",
    "cowgirl",
    "crawl",
    "crouch bounce twerk",
    "crouch twerk V2",
    "crouch twerk",
    "d all in yo stomach",
    "dababy lessgoo",
    "dance 28",
    "dap up",
    "dashie twerk V2",
    "death",
    "devious cave dive 1",
    "devious cave dive 3",
    "devious hand rub 2",
    "devious hand rub",
    "devious rub",
    "dick thrust",
    "dior lay twerk",
    "dive female transition",
    "dive in",
    "dive slide in",
    "dive thrust 1",
    "dive transition thrust",
    "dive transition",
    "diving in",
    "doggy thrust F",
    "doggy thrust M",
    "dont hide come here",
    "dont hide thrust 2",
    "dont hide thrust 3",
    "dont hide thrust",
    "dont hide twerk",
    "double gyat caress",
    "double gyat slap",
    "down thrust",
    "down twerk 2",
    "down twerk",
    "dream 2",
    "dti pose 28",
    "dual twerk 1",
    "dual twerk loop",
    "dwerk 3",
    "earthquake",
    "eating 2",
    "erm hi",
    "exes",
    "extended jerk",
    "fart",
    "fast clap",
    "feel up",
    "female rest",
    "field trip intro",
    "field trip",
    "fish thrust",
    "flip to twerk thingy",
    "flip twerk 1",
    "fly down",
    "fly in",
    "fnaf thrust",
    "footjob",
    "fortnite moves",
    "freaky ahh pose",
    "freaky blowjob",
    "fuck you 2",
    "ghetto twerk",
    "gif thrust",
    "gif twerk",
    "give shots",
    "gnarly twerk",
    "gomen nasai break dance",
    "gomen nasai breakdance 2",
    "gomen nasai breakdance",
    "gomen nasai",
    "goodbye nishiyama",
    "goofy thrust 2",
    "goofy thrust",
    "grab waist",
    "grind V2",
    "gyat slap 2",
    "hanging around",
    "headpat V2",
    "headpat",
    "headslide",
    "hello 2",
    "hip sway thrust 2",
    "hip sway thrust 3",
    "hip sway thrust",
    "hip twerk",
    "hitler salute",
    "hug intro",
    "hug short",
    "hug",
    "huh",
    "ice twerk 10",
    "ice twerk 11",
    "ice twerk 12",
    "ice twerk 13",
    "ice twerk 2",
    "ice twerk 3",
    "ice twerk 6",
    "ice twerk 8",
    "ice twerk 9",
    "ice twerk",
    "im so ATL vibe",
    "invis",
    "iron man pose",
    "its youuu",
    "jerk off 2",
    "jerk you off",
    "jiggy twerk loop",
    "jiggy twerk sequence",
    "jiggy twerk squat",
    "jiggy twerk thrust",
    "jitter thrust 2",
    "jump twerk",
    "kiss twerk",
    "kream twerk 2",
    "kream twerk 3",
    "lap dance",
    "laugh thrust 2",
    "laugh thrust",
    "laugh",
    "lay ride twerk",
    "lay twerk 4",
    "lay twerk 7",
    "lay twerk 75",
    "lay twerk V2",
    "lay twerk V5",
    "lay twerk polish",
    "lay twerk sequence",
    "lay twerking transition flip",
    "lay twerking",
    "laying twerk 3",
    "laying twerk",
    "lean twerk 2",
    "lean twerk",
    "look at that body 2",
    "look at that body",
    "lovely twerk",
    "luigi thrust 1",
    "luigi thrust 2",
    "maelay 2",
    "maelay",
    "me",
    "meat slap",
    "missionary",
    "mita shake",
    "motorboat",
    "multi twerk",
    "needy twerk",
    "nicki walk",
    "no guidance",
    "nod 3",
    "nope",
    "normal slap",
    "peep this lame ahh nigga",
    "polished ice twerk 5",
    "praise",
    "pro twerk",
    "push ups",
    "put a finger down",
    "reverse cowgirl",
    "ride it thrust",
    "rotate twerk",
    "run slide",
    "sassy super grind transition",
    "sassy thrust",
    "scared run",
    "scared",
    "scissor",
    "self ass slap",
    "sexy dance",
    "sexy thrust down",
    "sexy thrust",
    "sexy wiggle",
    "sgo thrust",
    "sharp bounce twerk",
    "sharp me",
    "sharp self ass slap",
    "sharp sgo thrust",
    "sharp split twerk sequence",
    "shocked death",
    "shocked",
    "shrug",
    "shy run to me",
    "shy thrust",
    "side fuck M",
    "side grab right",
    "side grind1",
    "simple thrust",
    "skeleton death reverse",
    "slap KO",
    "slow flip into thrust",
    "smooth dance",
    "sorry",
    "spine break death",
    "split twerk 7",
    "split twerk loop V2",
    "split twerk sequence",
    "squat thrust",
    "stab",
    "stand cowgirl F",
    "stiff dwerk",
    "stop wait a min",
    "stop",
    "stretch twerk",
    "suck it thrust",
    "super corkscrew twerk 2",
    "super corkscrew twerk",
    "super corkscrew",
    "super sassy grind thrust",
    "sway twerk 2",
    "sway twerk",
    "take it V2",
    "take shots 2",
    "take shots 4",
    "take shots 5",
    "take shots 6",
    "take shots 7",
    "take shots 8",
    "thank you thrust",
    "there goes my baby V2",
    "there goes my baby fail",
    "there goes my baby fall",
    "think hmm 2",
    "think hmm",
    "throw it in a circle",
    "thrust twerk sequence",
    "travis idle",
    "triple kill rub",
    "tt thrust",
    "twerk 8",
    "twerk 9",
    "twerk V2",
    "twerk sequence 2",
    "twerk sequence loop",
    "twerk sequence",
    "twerk sequence2",
    "twerk thingy",
    "underground",
    "up thrust 3",
    "up thrust 4",
    "up thrust",
    "ur the king",
    "vibe idle",
    "vibing",
    "wall hump measure",
    "wall hump thrust",
    "wall twerk 4",
    "wall twerk V2",
    "wall yap",
    "waving",
    "whos over there",
    "xstep",
    "you ladies alright",
    "you should see me in a crown",
    "zesty run",
}
